ydb_allow_format_drives: false
ydb_skip_data_loss_confirmation_prompt: false
ydb_enforce_user_token_requirement: true
ydb_storage_update_config: false
# ydb_use_dynamic_config - define how to configure dynamic nodes - static or dynamic configs
# Default value: false
ydb_use_dynamic_config: false
ydb_custom_dynconfig: ydbd-dyn-config.yaml.j2
ydb_config_v2: false
ydb_host_user: ydb
ydb_host_group: ydb
# ydb_database_quotas - set hard/soft quotas on every DB during creation 
ydb_database_quotas: false