---

# ydbops_local - control cluster from localhost
# values: false - use any static host for cluster control
#         true  - use localhost for cluster control
# Default value: false
ydbops_local: false

availability_mode: strong

ydb_enforce_user_token_requirement: true

ydbops_release_url: https://github.com/ydb-platform/ydbops/releases/latest/download/

