ydb_libidn_archive_unpack_options: ['--strip-component=1']

ydb_archive_unpack_options: ['--strip-component=1']
ydb_archive_force_install: false
ydb_binary_force_install: false

ydb_transparent_hugepages_enable: true
