- name: setup YDB on site
  hosts: "{{ playbook_hosts | default('ydb') }}"
  become: true
  tasks:
    - name: setup packages
      ansible.builtin.import_role:
        name: ydb_platform.ydb.packages
      when: ydb_tools_install|bool

    - name: configure system
      ansible.builtin.import_role:
        name: ydb_platform.ydb.system

    - name: configure unbound
      ansible.builtin.import_role:
        name: ydb_platform.ydb.unbound

    # - name: configure unbound site zone
    #   ansible.builtin.import_role:
    #     name: ydb_platform.ydb.site_unbound_zone

    # set hostnames to site fqdn here

    # check if names resolving

    # remove factory zone

    # obliterate disks if hostnames changed

    - name: setup ydb static nodes
      ansible.builtin.import_role:
        name: ydb_platform.ydb.ydbd_static

    - name: setup ydb dynamic nodes
      ansible.builtin.import_role:
        name: ydb_platform.ydb.ydbd_dynamic

    - name: setup node monitoring
      ansible.builtin.import_role:
        name: ydb_platform.ydb.monitoring_targets

- name: setup YDB monitoring on appliance factory
  hosts: monitoring
  become: true
  tasks:
    - name: setup monitoring service
      ansible.builtin.import_role:
        name: ydb_platform.ydb.monitoring_services
