repositories: []

preferences: []

configs:
  - dest: /etc/apt/apt.conf.d/50ydb
    content: |
      Acquire::Languages "none";
      APT::Cache-Limit "251658240";
      APT::Periodic::AutocleanInterval "1";
      APT::Periodic::MinAge "3";
      APT::Periodic::MaxAge "3";

packages:
  - atop
  - bash-completion
  - bind9-host
  - ca-certificates
  - curl
  - dnsutils
  - gdisk
  - iperf
  - iptables
  - jq
  - logrotate
  - lsof
  - nvme-cli
  - procps
  - python3-apt
  - python3-pip
  - python3-requests
  - rsync
  - strace
  - tar
  - tmux
  - tzdata
  - wget
  - xfsprogs
